### ISSUE TITLE
Need wordlists for Latin/Greek/Cyrillic *extended*

### ISSUE THREAD

**Issue by simoncozens** [samarskaya-and-partners/galvanizedjets#1]

**Comment by behdad** [comment]
Relevant: https://underware.nl/latin_plus/info/

**Comment by simoncozens** [comment]
One problem I have right now is that the site is structured in terms of *scripts*, but do we want to test in terms of *languages*?

**Comment by samarskaya** [comment]
We’re gonna want it structured in terms of scripts, but with an ability to limit or exclude languages within that.

**Comment by simoncozens** [comment]
How would you feel about merging the wordlist (OH) and extended (K̦ő) tests into one test, but have a dropdown/whatever to select the wordlist language?

**Comment by samarskaya** [comment]
Right right.

Here, on the right (what’s the word for quadrant but of thirds?) of the menu… we can hide the options for extended, punctuation, and numerics. And for now we can ignore the spacing page OH and focus (backwards) just on the kerning Ag.

I think what we’ll do is keep the language selection on the left (Latin, Greek, Cyrillic) and have an option for a right-click or pop-up that’ll then allow filtering within that.

**Comment by samarskaya** [comment]
(Also, apologies, site was a design experiment in creating a UI for an audience the size of a small dinner party.)

**Comment by simoncozens** [comment]
I've looked at the Wikipedia lists that @behdad generated. Unfortunately I don't think they're usable for this; there are far too many "non-words" (usernames, misspellings, just weird stuff from Talk pages etc.). Looking at this instead: https://github.com/hermitdave/FrequencyWords

**Comment by behdad** [comment]
> I've looked at the Wikipedia lists that @behdad generated. Unfortunately I don't think they're usable for this; there are far too many "non-words" (usernames, misspellings, just weird stuff from Talk pages etc.).

Right.  I'm happy to redo without non-articles if needed.

**Comment by behdad** [comment]
Also useful would be wiktionary.
