### ISSUE TITLE
Wordlists

### ISSUE THREAD

**Issue by samarskaya** [samarskaya-and-partners/galvanizedjets#13]
The wordlists seem especially junk. This might be part of a longer conversation, but how do we fix this? Maybe there could be a requirement for the word to appear several times to confirm it if from a pulled file and not a direct add, or maybe we make a note of later swapping to different dictionaries that provide the base word lists? Basically, you're much smarter than me at this. Let me know what you think.

**Comment by simoncozens** [comment]
I’ll work on rebuilding them. I’m imagining that a Python library which grabs words/sentences/paragraphs from Wikinews for an arbitrary language and then filters them in various ways (remove words with fewer than n occurrences, remove words not in script X, etc.) would be worth having - not just for this project but for other proofing uses.

**Comment by samarskaya** [comment]
<3

**Comment by simoncozens** [comment]
I'm working on this. I've published the [gobbet](https://github.com/simoncozens/gobbet) library to download Wikinews text in different languages, but there aren't any Wikinews instances for some of our languages, so I'm hacking it to use full Wikipedia. That's a lot bigger and will take quite a while to process...
