### ISSUE TITLE
Light Dark Icon

### ISSUE THREAD

**Issue by samarskaya** [samarskaya-and-partners/galvanizedjets#16]
Let's nix the small eye to the left of the size slider, and add in a bigger svg eye for that effect. It can go horizontally in the center of the menu, toward the top.

**Comment by samarskaya** [comment]
Icons: https://www.dropbox.com/sh/o7nb9e1rqh11haq/AAAhes5aHYM8_CeS1XeoPuxYa?dl=0

**Comment by simoncozens** [comment]
On and off are the same?

**Comment by simoncozens** [comment]
No, it's OK, I got another SVG from somewhere.

**Comment by samarskaya** [comment]
Yeahs, they're diff because one has a transparent background and another a white one.
