### ISSUE TITLE
Variable font support

### ISSUE THREAD

**Issue by simoncozens** [samarskaya-and-partners/galvanizedjets#2]
" Do you think you can integrate one of the JS tiny libraries to enumerate sliders and add those ala the OpenType Features panel?"

"Re varfonts, here's Monotype's wrapper around opentype.js: https://github.com/Monotype/variableFont.js "

I also found [pomax/Font.js](https://github.com/Pomax/Font.js) which also reports the varfont axes.

Adding this should be easy apart from the dragged-in fonts. These are stored as `src:url(data:...)` blobs in the CSS. Both font.js and variablefont.js want to read the font file from a URL I don't know how they'll deal with a data URL but I'll try it.

**Comment by behdad** [comment]
> Adding this should be easy apart from the dragged-in fonts. These are stored as `src:url(data:...)` blobs in the CSS. Both font.js and variablefont.js want to read the font file from a URL I don't know how they'll deal with a data URL but I'll try it.

I'm super positive the data URL can be "fetched" from just fine.
